import {AbstractCreditDebitPendingPayoutNotificationData} from './AbstractCreditDebitPendingPayoutNotificationData';

export interface CreditNotificationData extends AbstractCreditDebitPendingPayoutNotificationData {

}
