import {AbstractCreditDebitPendingPayoutNotificationData} from './AbstractCreditDebitPendingPayoutNotificationData';

export interface DebitNotificationData extends AbstractCreditDebitPendingPayoutNotificationData {

}
