import {AbstractCreditDebitPendingPayoutNotificationData} from './AbstractCreditDebitPendingPayoutNotificationData';

export interface PendingNotificationData extends AbstractCreditDebitPendingPayoutNotificationData {

}
