export interface GetWithdrawalsResponseDataEntry {

  /**
   * Reference code for the withdrawal generated by Trustly.
   */
  reference?: string;

  /**
   * Date and time when the withdrawal was last updated.
   */
  modificationDate?: string;

  /**
   * OrderID of the withdrawal
   */
  orderId?: string;

  /**
   * Date and time when the withdrawal request was received.
   */
  datestamp?: string;

  /**
   * The current state of the withdrawal.
   * <p>
   * Examples are:
   * <ul>
   *   <li>EXECUTING</li>
   *   <li>EXECUTED</li>
   *   <li>PENDING</li>
   *   <li>QUEUED</li>
   *   <li>PREPARING</li>
   *   <li>PREPARED</li>
   *   <li>BOUNCED</li>
   *   <li>ERROR</li>
   *   <li>FAILED</li>
   *   <li>RETURNED</li>
   *   <li>CONFIRMED</li>
   * </ul>
   *
   * <p>
   * It's important that no logic is built on the merchant side based on any specific transferState.
   * New states can be added, and existing states can be changed or removed without notice.
   */
  transferState?: string;

  /**
   * The amount of the withdrawal.
   */
  amount?: string;

  /**
   * The accountid of the receiving account.
   */
  accountid?: string;

  /**
   * The currency of the withdrawal.
   */
  currency?: string;

  /**
   * The estimated date and time for when the funds will be available on the receiving bank account.If this information is not available it
   * will be null.
   */
  eta?: string;
}
