name: Publish Package to npmjs

on:
  push:
    tags: ['*.*.**']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set git identity
        run: |
          git config user.name ci-bot
          git config user.email code.sign@trustly.com

      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'
      - run: npm ci
      - name: Set version based on tag name
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}
          npm version --allow-same-version --force "$TAG_NAME"
      - run: npm run build
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
